FastFFT: part 30
Fix errors found by CI:

- release_build_full_no_experimental.yml
- undefined reference to `AtomicCoordinatesAssetPanel::AtomicCoordinatesAssetPanel(wxWindow*)`
    - FIXED by adding to regular cisTEM_sources in Makefile.am (outside include guard). Also changed noinst_headers even though that is not revealed in this error.

- debug_build_cpu_only.yml
- Error: Blank answer in scripted mode, exiting...
- CTF find inputs in console test section
    - FIXED scripts/testing/test_and_benchmark.sh by adding a line for "find sample thickness" as no in the script prompts

- cisTEM GPU release, GNU MKL
- batched_search.h
    - The warning occurs at line 83 due to a comparison between int and std::vector<float>::size_type
    - FIXED change loop counter to size_t

- match_template.cp
    - line 872. The error indicates that data_sizer appears more than once in the data clauses of the OpenMP
    - FIXED delete extra data_sizer in shared clause